spring:
  profiles:
    active: dev
  application:
    name: nexusmall-auth
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    password: ${REDIS_PASSWORD:}
    timeout: 5000
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
        namespace: public # 命名空间
        group: DEFAULT_GROUP # 分组

# 安全配置
security:
  jwt:
    secret-key: mySecretKeyForJWTGenerationAndValidation
    expire-time-in-ms: 86400000 # 24小时

# 暴露所有端点用于监控
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 服务端口
server:
  port: 8000

