spring:
  config:
    import: "optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}"
  profiles:
    active: dev
  application:
    name: nexusmall-order
  redis:
    host: ${REDIS_HOST:10.10.1.1}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    password: ${REDIS_PASSWORD:123456}
    timeout: 5000
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        file-extension: yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 11000
