spring:
  profiles:
    active: dev
  application:
    name: nexusmall-gateway
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    password: ${REDIS_PASSWORD:}
    timeout: 5000
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://nexusmall-auth
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: lb://nexusmall-product
          predicates:
            - Path=/product/**
        - id: order-service
          uri: lb://nexusmall-order
          predicates:
            - Path=/order/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    secret-key: mySecretKeyForJWTGenerationAndValidation
    expire-time-in-ms: 86400000

server:
  port: 88
