spring:
  profiles:
    active: dev
  application:
    name: nexusmall-gateway
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    password: ${REDIS_PASSWORD:}
    timeout: 5000
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务自动发现
          lower-case-service-id: true # 服务ID小写
      routes:
        - id: product-service
          uri: lb://nexusmall-product # 使用负载均衡访问product服务
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1 # 去掉前缀
        - id: order-service
          uri: lb://nexusmall-order
          predicates:
            - Path=/order/**
      globalcors:  # 跨域配置
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

# 暴露所有端点用于监控
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 服务端口
server:
  port: 88

